-- Databricks notebook source
-- MAGIC %md
-- MAGIC
-- MAGIC ## How to migrate IDENTITY columns from a Data Warehouse to DBSQL / Delta Lakehouse
-- MAGIC
-- MAGIC ## Summary
-- MAGIC Quick notebook showing how to properly migrate tables from a data warehouse to a Delta table where you want to retain the values of existing IDENTITY key values and ensure that the IDENTITY generation picks up from the most recent IDENTITY column value

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC
-- MAGIC ### Steps to migrate key properly
-- MAGIC
-- MAGIC 1. Create a table with id columns such as: GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)
-- MAGIC 2. Backfill existing data warehouse tables with an INSERT INTO / MERGE from a snapshot of the datawarehouse table
-- MAGIC 3. Run command: ALTER TABLE main.default.identity_test ALTER COLUMN id SYNC IDENTITY; to ensure that the newly inserted values pick up where the data warehouse left off on key generation
-- MAGIC 4. Insert new identity values with new pipelines (or leave out column and let it auto-generate)

-- COMMAND ----------

-- DBTITLE 1,Simple End to End Example

CREATE OR REPLACE TABLE main.default.identity_test (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name STRING DEFAULT 'cody'
  )
  TBLPROPERTIES('delta.feature.allowColumnDefaults' = 'supported', 'delta.columnMapping.mode' = 'name')
;

-- Simulate EDW migration load with existing keys
INSERT INTO main.default.identity_test (id,name) 
VALUES (5, 'cody'), (6, 'davis');


SELECT * FROM main.default.identity_test;


-- Simulate new load incrmentally

INSERT INTO main.default.identity_test (name) 
VALUES ('cody_new'), ('davis_new');

-- BAD! ID keys get messed up
SELECT * FROM main.default.identity_test;

-- FIX
ALTER TABLE main.default.identity_test ALTER COLUMN id SYNC IDENTITY;

-- try again
INSERT INTO main.default.identity_test (name) 
VALUES ('cody_fix'), ('davis_fix');

SELECT * FROM main.default.identity_test;


