{% macro create_bronze_users_identity_table() %}
-- Seprately DDL creation for doing things like custom / rigid schema DDL or Identity columns
-- Use Sparingly, as DBT approaches DDL as being done inconjunction with the data

CREATE TABLE IF NOT EXISTS {{target.catalog}}.{{target.schema}}.bronze_users
(
userid BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
gender STRING,
age INT,
height DECIMAL(10,2), 
weight DECIMAL(10,2),
smoker STRING,
familyhistory STRING,
cholestlevs STRING,
bp STRING,
risk DECIMAL(10,2),
ingest_timestamp TIMESTAMP
)
CLUSTER BY (ingest_timestamp)

{% endmacro %}