{% macro create_bronze_sensors_identity_table() %}
-- Seprately DDL creation for doing things like custom / rigid schema DDL or Identity columns
-- Use Sparingly, as DBT approaches DDL as being done inconjunction with the data

CREATE TABLE IF NOT EXISTS {{target.catalog}}.{{target.schema}}.bronze_sensors
(
Id BIGINT GENERATED BY DEFAULT AS IDENTITY,
device_id INT,
user_id INT,
calories_burnt DECIMAL(10,2), 
miles_walked DECIMAL(10,2), 
num_steps DECIMAL(10,2), 
timestamp TIMESTAMP,
value STRING,
ingest_timestamp TIMESTAMP
)
CLUSTER BY (ingest_timestamp)

{% endmacro %}